
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyectoimportaciones_v1
{

using System;
    using System.Collections.Generic;
    
public partial class SalidaImportacion
{

    public int id { get; set; }

    public string CodigoCliente { get; set; }

    public string NombreCliente { get; set; }

    public string NumeroFactura { get; set; }

    public string CantidadCompra { get; set; }

    public string NumeroImportacion { get; set; }

    public Nullable<System.DateTime> FechaSalidaImportacion { get; set; }

}

}
